# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: Your awesome title
email: your-email@example.com
description: "site description"

author: Ravi Riley

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

#plugins:
#  - jekyll-feed

footer:
  links:
    - title: "Twitter"
      icon: "fab fa-twitter"
      url: https://twitter.com
    - title: "Facebook"
      icon: "fab fa-facebook-f"
      url: https://facebook.com
    - title: "LinkedIn"
      icon: "fab fa-linkedin-in"
      url: https://linkedin.com
    - title: "GitHub"
      icon: "fab fa-github"
      url: https://github.com/raviriley
    - title: "Instagram"
      icon: "fab fa-instagram"
      url: https://instagram.com