url: https://raviriley.github.io
baseurl: "/agency-jekyll-theme"

# Site settings
title: Your Title
email: your-email@domain.com
description: "Description"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/
  - title: linkedin
    url: https://www.linkedin.com/

# Postal address (add as many lines as necessary)
address:
  - line: 1234 Example Ave
  - line: Somewhere, EX 12345

# Build settings
markdown: kramdown
permalink: pretty